name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix Missing libtinfo5 (Ubuntu 24.04 Fix)
        run: |
          # Download the library from the official Ubuntu mirrors
          wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb
          sudo dpkg -i libtinfo5_6.4-2_amd64.deb
          rm libtinfo5_6.4-2_amd64.deb

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Build APK
        run: |
          # The logic to build the file
          yes | /home/runner/.local/bin/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: snakeladder-apk
          path: bin/*.apk
